### PR TITLE
Migration flow fixes

### LINKED ISSUE #2058: [BUG] Improve fast vault migration flow
**Describe the bug**
The migration fast vault flow is not properly implemented, please follow the [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=35806-33248&t=0Zxhi3NCGNCIB7DZ-4). Especially for the Password view copy text 

System:
 - Version 15.3

### PR DESCRIPTION
**Pull request by Rockindash**
Updated vault migration flow to include new views, Fixes #2058

**Screenshot**
Simulator Screenshot - iPhone 15 Pro - 2025-04-17 at 02 35 56
Simulator Screenshot - iPhone 15 Pro - 2025-04-17 at 02 35 37
Simulator Screenshot - iPhone 15 Pro - 2025-04-17 at 02 35 28
Simulator Screenshot - iPhone 15 Pro - 2025-04-17 at 02 35 22

## Summary by CodeRabbit

- **New Features**
  - Introduced a dedicated vault upgrade screen with animated visuals and localized messaging.
  - Enhanced migration and upgrade flows with new UI elements and navigation for vault backup and migration processes.

- **Improvements**
  - Added new localized strings for vault upgrade and migration in English, German, Spanish, Croatian, Italian, and Portuguese.
  - Updated backup and migration flows to differentiate between standard and migration scenarios, providing tailored instructions and navigation.
  - Improved visual feedback and navigation logic for backup, migration, and verification steps across multiple views.
  - Added validation to ensure selected vault matches scanned data during reshare and migration processes.
  - Extended navigation and view initializations to include selected vault context for improved flow consistency.

- **Style**
  - Updated icons and refined UI layouts for a more consistent user experience.

- **Bug Fixes**
  - Minor UI and navigation adjustments to ensure smoother transitions during backup and migration.

### CODE REVIEW

File: VultisigApp/VultisigApp/Views/Keygen/PeerDiscoveryView.swift [hunk 1]
```diff
@@ -191,15 +191,15 @@ struct PeerDiscoveryView: View {
             showInfoSheet = false
             return
         }
-        switch self.tssType {
+        
+        switch self .tssType {
```
Comment (johnnyluo) [inline VultisigApp/VultisigApp/Views/Keygen/PeerDiscoveryView.swift:195]: There is a space between `self` and `.tssType` , is it intention?

**Review by johnnyluo — APPROVED** [review]
LGTM

**Comment by johnnyluo** [comment]
@Rockindash could you please fix the typo?
