### PR TITLE
Swap cancel error

### LINKED ISSUE #2255: [BUG]Swap - stucked error
**Describe the bug**
on swap there is stucked error "canceled"

**To Reproduce**
1. Go to swap
2. Chose exist assets and set correct valu
3. Click switch button (get error canceled)
4. switch back (still exist error )

Image

https://www.loom.com/share/7beb7ed7922c4f2fa207c76bb580ed6b

System:

**Additional context**
v 1.18.1

### PR DESCRIPTION
**Pull request by Rockindash**
## Description

Swap validation logic updated to handle cancelled state

Fixes #2255

## Which feature is affected?
- [ ] Swap - Select Polygon and BNB chain. And tap on interchange button.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

- **Bug Fixes**
  - Cancelled network requests during quote updates are no longer shown as errors in the UI.
  - Existing errors are now cleared before initiating a swap action to ensure accurate error display.

- **New Features**
  - Swap details are now refreshed automatically after swapping coins, providing up-to-date information.

### CODE REVIEW

File: VultisigApp/VultisigApp/Views/Swap/SwapCryptoDetailsView.swift [hunk 1]
```diff
@@ -189,11 +189,18 @@ struct SwapCryptoDetailsView: View {
...
     private func handleSwapTap() {
+        swapViewModel.error = nil
         buttonRotated.toggle()
         swapViewModel.switchCoins(tx: tx, vault: vault)
         let fromChain = swapViewModel.fromChain
         swapViewModel.fromChain = swapViewModel.toChain
         swapViewModel.toChain = fromChain
+        swapViewModel.refreshData(tx: tx, vault: vault)
+//        let fromChain = swapViewModel.fromChain
+//        swapViewModel.fromChain = swapViewModel.toChain
```
Comment (johnnyluo) [inline VultisigApp/VultisigApp/Views/Swap/SwapCryptoDetailsView.swift:200]: @Rockindash could you please just remove these?

**Review by johnnyluo — APPROVED** [review]
LGTM
