### PR TITLE
Skip button disabled for BackupVaultNowView

### LINKED ISSUE #1634: [Update] Disable the skipping of backup for secure vaults
**Describe the bug**
Remove skip button on BackupNowView for secure vaults

### PR DESCRIPTION
**Pull request by Rockindash**
Skip button disabled for BackupVaultNowView, Fixes #1634

### CODE REVIEW

File: VultisigApp/VultisigApp/Views/Vault/BackupVaultNowView.swift [hunk 1]
```diff
@@ -37,19 +37,19 @@ struct BackupVaultNowView: View {
     var content: some View {
         VStack(spacing: 0) {
             HStack {
-                if showSkipButton {
-                    skipButton
-                        .opacity(0)
-                        .disabled(true)
-                }
+//                if showSkipButton {
```
Comment (johnnyluo) [inline VultisigApp/VultisigApp/Views/Vault/BackupVaultNowView.swift:40]: can you please remove it @Rockindash ?  once we remove , usually we won't get it back
also git has history

Comment (Rockindash) [reply VultisigApp/VultisigApp/Views/Vault/BackupVaultNowView.swift:40]: Just removed the code. Can you please review it again.

**Review by johnnyluo — APPROVED** [review]
