### PR TITLE
fix: updated error style on Keygen

### LINKED ISSUE #3669: [BUG] - The icon shown in the duplicate vault error screen during key generation is clickable
*Summary:* The icon shown in the duplicate vault error screen during key generation is clickable, though it should not be interactive.

*Steps to Reproduce:*
1. Open the app on Android v1.0.90 (90).
2. Start the keygen process.
3. Trigger a scenario where a duplicate vault already exists.
4. Observe the error screen.
6. Tap on the icon and observe that it is clickable.

image

### PR DESCRIPTION
**Pull request by gastonm5**
## Description

Please include a summary of the change and which issue is fixed. 

Fixes #3669 

## Which feature is affected?
- [ ] Create vault ( Secure / Fast) - Please ensure you created a Secure vault & fast vault
- [ ] Sending  - Please attach a tx link here
- [ ] Swap - Please attach a tx link for the swap here
- [ ] New Chain / Chain related feature  -  Please attach tx link here

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

## Summary by CodeRabbit

* **Localization**
  * Added translated messages (EN, DE, ES, HR, IT, PT, ZH‑Hans) for vault name conflicts, vault type mismatches, and incorrect vault selection.

* **Improvements**
  * Replaced freeform error text with structured error cases surfaced with localized titles and descriptions.

* **UI Changes**
  * Join/keygen flow now shows a dedicated error view on failure and removes the previous file-picker UI.

* **Navigation**
  * Scanner/navigation flows simplified to use callback-driven navigation instead of multiple bound state flags.

### CODE REVIEW

File: VultisigApp/VultisigApp/Views/Keygen/JoinKeygenView.swift [hunk 1]
```diff
@@ -112,15 +112,17 @@ struct JoinKeygenView: View {
...
-
-            filePicker
+        if let error = viewModel.error {
+            ErrorView(
+                type: .warning,
+                title: error.errorTitle,
+                description: error.errorDescription,
+                buttonTitle: "tryAgain".localized
+            ) {
+                showFileImporter.toggle()
```
Comment (johnnyluo) [inline VultisigApp/VultisigApp/Views/Keygen/JoinKeygenView.swift]: This might related to your change , but I think the logic is not correct , when "try again" it should probably just go to mainview in this case 

however this one bring up file selector

Comment (gastonm5) [reply VultisigApp/VultisigApp/Views/Keygen/JoinKeygenView.swift]: mm yeah, it makes sense
