### PR TITLE
Retrieve network id from THORChain

### LINKED ISSUE #930: [BUG] THORChain retrieve ChainID from RPC endpoint
**Describe the bug**
Currently,  for THORChain , chain-id is set using WalletCore's coin.ChainID , which is stored in walletcore , usually it doesn't change , but THORChain is going to do a hardfork soon , thus the chainID will be changed

Retrieve THORChain's chain-ID from RPC endpoint  https://rpc.ninerealms.com/status

### PR DESCRIPTION
**Pull request by johnnyluo**
fixes #930 

When THORChain hardfork , it will change the chain id , this allow Vultisig continue to work without an update

### CODE REVIEW

File: VultisigApp/VultisigApp/Services/Thorchain/ThorchainService.swift [hunk 1]
```diff
@@ -97,4 +98,14 @@ class ThorchainService: ThorchainSwapProvider {
         
         return .zero
     }
+    
+    func getTHORChainChainID() async throws -> String  {
+        if !network.isEmpty {
+            return network
+        }
+        let (data, _) = try await URLSession.shared.data(from: Endpoint.thorchainNetworkInfo)
```
Comment (enriquesouza) [inline VultisigApp/VultisigApp/Services/Thorchain/ThorchainService.swift:106]: Can you cache it for a long time?

**Review by enriquesouza — APPROVED** [review]
LGTM, but we should cache it

File: VultisigApp/VultisigApp/Services/Thorchain/ThorchainService.swift (hunk 1 above)
Comment (johnnyluo) [reply VultisigApp/VultisigApp/Services/Thorchain/ThorchainService.swift:106]: it only does this once
